### ISSUE TITLE
ImportError: libcublas.so.11:cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by alyymsong** [quic/aimet#2295]
Hi, I have installed AIMET on Ubuntu and runing an AIMET Examples.
I encountered the following error: ImportError: libcublas.so.11:cannot open shared object file: No such file or directory
and then i try this" apt-get install libculas-11-0", but i I encountered "unable to locate package libculas-11-0"
How to resolve it?

**Comment by quic-mangal** [comment]
@quic-akhobare @quic-bharathr could you help answer this?

**Comment by quic-akhobare** [comment]
Hi @alyymsong - it seems you don't have CUDA installed. Either you can run in CPU mode - use the CPU-only AIMET whl files, or install CUDA.. 

To install CUDA: https://quic.github.io/aimet-pages/releases/latest/install/#:~:text=Install%20GPU%20packages,%C2%B6

**Comment by Nishq-AkulaTech** [comment]
Hi @quic-akhobare, any suggestions for what to do if I'm using google colab to use the tf_gpu variant? I am able to access a T4 GPU. 

Appreciate the help!

**Comment by quic-kyunggeu** [comment]
This issue is resolved once and forever in aimet-torch 2.x.
In 2.x, we don't use libpymo anymore. No more path error, undefined symbols, segfault, etcetc
